### ISSUE TITLE
NetGuard blocks Wi-Fi calling?

### ISSUE THREAD

**Issue by nickzman** [M66B/NetGuard#205]
Pardon me if this is a duplicate of issue #42, but I noticed that with NetGuard turned on, Wi-Fi calling doesn't work anymore. Can I use NetGuard and Wi-Fi calling at the same time? If so, then what do I need to enable to make this work?

**Comment by M66B** [comment]
I don't know what you mean by WiFi calling.
Maybe you can better ask this on the XDA NetGuard forum.

**Comment by Gitoffthelawn** [comment]
I'm 99% sure he means VoIP calling.  He most likely has NetGuard blocking a component required for VoIP.  Perhaps someone can help him on XDA.

**Comment by M66B** [comment]
I use VoIP calling quite frequently myself and I am pretty sure this works with NetGuard enabled.

**Comment by nickzman** [comment]
I am not talking about VoIP calling; I am talking about Wi-Fi calling, a service offered by T-Mobile USA that's enabled on stock Android in Settings -> More -> Wi-Fi calling.

Searching around, it appears that Wi-Fi calling uses UDP ports 500 and 4500. Does NetGuard do anything to those ports? I tried turning off Wi-Fi & mobile blocking by default, and it didn't make a difference.

**Comment by M66B** [comment]
NetGuard doesn't do anything with specific ports. NetGuard solely routes internet traffic for applications you select into a VPN sinkhole. Some services, like tethering and apparently WiFi calling doesn't work, because Android doesn't support these services while a VPN is active. This is an Android problem, which the application cannot work around.
