### ISSUE TITLE
Add F-Droid link in README.md

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#23]
It's not up to date since this is going pretty fast right now but it helps.

Link: https://f-droid.org/repository/browse/?fdfilter=netguard&fdid=eu.faircode.netguard

**Comment by pylerSM** [comment]
Did you get permission to publish it there from M66B? I believe he said that he hadn't agree with their signature process.

**Comment by licaon-kter** [comment]
You mean [this](http://forum.xda-developers.com/showpost.php?p=63561767&postcount=48).
I did not publish it there, although I'm not sure how GPL3 and the whole APK signature collide.

But it ould be useful to add this info in the README.md at least *"please don't compile and redistribute with your signature blahblah"*.

**Comment by licaon-kter** [comment]
Now that you have the PlayStore beta thing, would you still build them for Github?

I'm stuck on 0.9-debug-2 or whenever F-Droid builds them. :(

**Comment by M66B** [comment]
There is deliberately no GitHub release for 0.10, since I want to have the Play store release tested. The next release will be both in the Play store and on GitHub.

F-Droid builds are not supported and one of the reasons is that I have no control over when builds are done (imagine the need for a crash release to prevent further damage).

**Comment by licaon-kter** [comment]
Cross link: https://f-droid.org/forums/topic/encouraging-f-droid-participation-by-developers/

**Comment by M66B** [comment]
I have just commented at F-Droid.

**Comment by M66B** [comment]
For reference: https://blog.torproject.org/blog/deterministic-builds-part-one-cyberwar-and-global-compromise
