### ISSUE TITLE
Telephony options  on non-3G

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#257]
Non 3G tablet
CM13

Options availablo wrongfully for: ignore national roaming and treat 2/3/4G as unmettered.

Trying to activate then yields the permission manager asking for telephony stuff access.

**Comment by M66B** [comment]
This test is known to fail on some devices, because of incorrect Android configuration / bugs:
https://github.com/M66B/NetGuard/blob/master/app/src/main/java/eu/faircode/netguard/Util.java#L111

Somebody already contributed a workaround for the inverse situation.
I will think of a workaround for your situation, but I am not very hopeful.

**Comment by M66B** [comment]
I see no way how I can fix this or workaround it.

**Comment by M66B** [comment]
See also #267
