### ISSUE TITLE
App access address pop-up shifts position

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#261]
http://imgur.com/FHlLdsE

I guess on access list update.

Maybe a "disable realtime update" toggle is needed here too?

**Comment by M66B** [comment]
I know, but I am not sure what to do about it.

There are two options:

* Attach the popup menu to the entry (current situation). This is convenient, since the popup is close to the entry, but has as disadvantage the reported problem, it shifts to the top as new entries arrive
* Attach the popup menu to a fixed point. This is inconvenient, since the popup can be far from the entry.

**Comment by licaon-kter** [comment]
Simple, no real time update while app details is open.

**Comment by M66B** [comment]
While the popup menu is open then, but that is not as easy as it seems.

**Comment by licaon-kter** [comment]
No, not link it with the popup, no update what so ever.
