### ISSUE TITLE
Split access notification for allowed and blocked

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#294]
My initial https://github.com/M66B/NetGuard/issues/231 was in the vein of AFWall+, where you can get a toast on a blocked connection.

That got morphed into the notification, but if I allow an app I don't really care any more where it connects to (except I can load hosts to block some "bad" destinations that is) and the wave of notifications has no use for me.

So, my idea is to split the notification into a blocked option too.

That could help in finding some app dependencies or could influence decisions regarding the usefulness of said app, case in point for me ES Explorer: it hammers the internet, although it's blocked and not started by me (I guess it listens to the connection on intent), and the newer versions brought a lot of ads.

**Comment by M66B** [comment]
I think it is important to know which traffic was allowed too, since it could be unwanted traffic.

The notification will only be there when there is a new address discovered, listing all allowed/blocked addresses without rules (block or allow) in reverse chronological order, so you can better judges what happens and happened.

Isn't this good enough?

**Comment by licaon-kter** [comment]
I agree it's important, it's just that I do not want to see it, but I want to see the blocked traffic.

**Comment by M66B** [comment]
Given the use case you describe, isn't it an option to disable the notifications for the application. There is a check box for that in the application drill down.
