### ISSUE TITLE
Delete Log Entries older then x Days

### ISSUE THREAD

**Issue by tbv2005** [M66B/NetGuard#348]
As you asked for Enhancements on XDA following option would be nice: 
Delete Log Entries older then X days. Reason: if you don't clear your log from time to time it will take more and more time to open (logically). Either have it hardcoded to delete Log entries older then 2 or maybe 5 days or even more perfect make an option in the settings where you can choose (1 / 2 / 7 / 14 / Never). Not sure if feasible, just something to think about.

**Comment by M66B** [comment]
The traffic log is meant to assist in finding problems, but it is not intended to be active continuously, because it will use extra battery power. I will think about this, but instead I might limit the time the log can run.

The number of entries in the log will not make things slower, but log entries will use storage space.

**Comment by tbv2005** [comment]
All right, just to be clear I'm not saying more log entries make things slower. Just opening the log itself takes more time if you have it always on and don't clear. I use it to see what applications tries to connect to which destination. I know that's also visible in the main view when you expand the app, but I find it more convenient to see it all in one list then to expand the apps one by one manually. To be honest I don't care about the extra battery power if I have such an overview, not sure if I would be the only one or if there more people having the same opinion as me.
In the end up to you how you go forward :-) - I just can give my input why I'm using it and why I would find this as an good option.
PS: To find out if people would like or not maybe you introduce the same way for NetGuard as you did for XPrivacy. If an Enhancement get's more then x rates you take it into consideration, otherwise it's automatically denied (just an idea).

**Comment by M66B** [comment]
The loading of the traffic log is not slower with more entries in the log, since loading is on demand.

Voting is a nice idea, but in practice it doesn't work, because to few people are really involved.

If you have enough storage space, the size of the log will not soon be a problem.

What do you think about the idea to limit the size of the log, for example to 1000 entries?

**Comment by tbv2005** [comment]
I think that's even a better idea!
