### ISSUE TITLE
Notify on GitHub update

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#349]

**Comment by M66B** [comment]
Latest release JSON: https://api.github.com/repos/M66B/NetGuard/releases/latest

**Comment by Roboe** [comment]
Is this a good idea for F-Droid users? Non-matching signing keys prevent the app to be installed. Is there a way to check the signing key instead of whichever app store installed?

Also, while using NetGuard to avoid mobile comsumption (one of its possible uses), downloading an APK by error is not expected...

**Comment by M66B** [comment]
Version 2.4 has an option to disable update notifications if you are concerned.
F-Droid releases are not supported, see the FAQ why.

**Comment by Roboe** [comment]
AFAIK, your builds are not reproducible, either (nor any APK out there), but I respect your decision.

Thanks for making it optional! :)
