### ISSUE TITLE
Split settings for user/system applications

### ISSUE THREAD

**Issue by M66B** [M66B/NetGuard#350]

**Comment by M66B** [comment]
This was asked on XDA, but I am not really a fan of the idea, since it would double the number of settings and also double the complexity.

**Comment by tbv2005** [comment]
I could understand why it has been asked. Originally I setup that everything is allowed and blocked what I wanted. Then changed the setting to block everything and suddenly everything was blocked, so changed back to everything allow as I didn't want to allow all apps I haven't changed before manually.
I didn't comment on the request on XDA because I also thought that setting menu would be to full and could be irritating.
Another idea: I just checked the exported setting XML. It looks like you only save apps in there where settings have been changed from default. How about exporting everything (all apps) with there current state. On import make an option if you want to import Everything or Just apps or Just settings. With that you can make an export, change the settings and then import the app settings you currently had.
Not sure if feasible and if it would be logic to everybody, just an idea.

**Comment by M66B** [comment]
I think that is too complicated, especially because I think just a few people would use this. NetGuard is mostly used by another type of people than XPrivacy.


tbv2005 <notifications@github.com> schreef op 27 februari 2016 16:13:51 CET:

**Comment by tbv2005** [comment]
Yes, maybe you're right.... - I can also live with having everything enabled and block installed apps via the notification. Was just an idea. ( and once I find the time I will change the setting and then allow all apps manually :-) )

**Comment by M66B** [comment]
I have decide to not add extra option for this, since IMHO this makes things overly complicated.
