### ISSUE TITLE
Add Profile option

### ISSUE THREAD

**Issue by mahmutelmas06** [M66B/NetGuard#389]
It is a request to add profile feature to switch manually.

**Comment by M66B** [comment]
Profiles are inconvenient because they need to be operated manually. Conditions like 'When screen is on' are on the other hand convenient because they work automatic. Therefore there will be no profiles, but you are welcome to propose a new conditions, but they needs to be generally usable for inclusion.

As a workaround you can use the export/import feature to apply specific settings in specific circumstances.
