### ISSUE TITLE
My honest review for NetGuard v2.17 F-Droid

### ISSUE THREAD

**Issue by martinkrafft** [M66B/NetGuard#407]
NetGuard v2.17 F-Droid
Rate: 4/10.
Hey, I really want to give more scores, but...
---

Summary:
No offense, but NetGuard need more improvement.
Also, I'm surprised this app is exist on FOSS market(fdroid).

Details:
What to begin...

> BUGS
1. When I tried to set "VPN DNS" to 127.0.0.1, app throws "java.lang.IllegalArgumentException:
Bad address" error, forcing me to use Google DNS. (127.0.0.1 for Orbot's DNS)
2. After I set "Hosts file download URL" to empty, NetGuard set this value again.
Why I can't disable it? If I can't, I say it "Phone Home Activity(*1)".

> IMPROVEMENTS TO DO
1. Add an option to use "http proxy" to connect outside for your app.
"Hosts file download" & "update check" function.
2. "Enable IPv6 Traffic" option - If I disable it, will NetGuard stop filtering IPv6? Need more description.
3. Try to split the loooong menu to category, for example, "Default" "Design" "Network" "Advanced" "Backup" "Info".
4. Add "Sort by 3G permission" & "Sort by Wifi permission".
5. Describe "Subscription" and "Pro features". I guess you're making a "paid app".
6. Try https://apkpure.com/noroot-data-firewall/com.jianjia.firewall and learn from it.

> SECURITY/CRITICAL
1. "VPN DNS" is defauled to "8.8.8.8". I don't trust Google and due to its
hostile nature, it MUST NOT be used as default. Change it to OpenDNS(use.opendns.com for info)
or OpenNIC instead. Related issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761658
2. You are forcing people to use/access netguard.me server. Related Bugs#2.
If netguard.me is compromized by virus(malvertising,etc), all people who connect to it will f**ked.
So, this must be "opt-in by default(not optout)", and also, let user to disable/switch to other source.
3. Same thing goes to "[X] Check Update github" option. I use Fdroid to do that, so let's just turn off
by default! (If your app make a connection, who will pay for Internet connection fee? Me, right?)
3. If you're making true open source & free (not paid) app, try to remove "billing service" "read phone identity"
permission, which is suspicious to open source software. Why do you require them for "Firewall" app!?

Conclusion:
I expected NetGuard as a pure firwall.
However, NetGuard connect to the Internet, especially netguard.me BY DEFAULT without user consent(on by default).
Firewall app should not connect anywhere unless the user allow it to do it.
Fiwall should allow only selected apps; deny everything else.
Current review, I see netguard is a "basket with a hole". Need some ducttape to fix that.

**Comment by martinkrafft** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/436

**Comment by licaon-kter** [comment]
You did not read [FAQ#15](https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ15), did you?

> 1, When I tried to set "VPN DNS" to 127.0.0.1

No, you use port forwarding: UDP/53/127.0.0.1/port/Orbot
So, it won't matter what VPN DNS points to, it will get redirected to Orbot.

> 2. After I set "Hosts file download URL" to empty, NetGuard set this value again.

No, it does not, that's the "hint value" that's just shown there for people to understand where to put it, it's a bit greyer coloured.

> 1. Add an option to use "http proxy" to connect outside for your app.

No, you use port forwarding: UDP/443/external-adress/proxyport/nobody, same for port 80.

> 2. "Enable IPv6 Traffic" option - If I disable it, will NetGuard stop filtering IPv6?

It should, do test, get a logcat/PCAP and report it as an actual issues if it does not.

> 3. Try to split the loooong menu to category

Why are you using the Settings menu so often that this is a problem?

> 4. Add "Sort by 3G permission" & "Sort by Wifi permission".

Not sure if it helps so much, why bother?

> 5. Describe "Subscription" and "Pro features". I guess you're making a "paid app".
1. "VPN DNS" is defauled to "8.8.8.8". I don't trust Google and due to its
hostile nature,
_Subscription_ is something related to the network connections.
_Pro features_ means that some non-essential features (app is already feature complete without these) can be bought, like more themes. If you would like to support bug fixing or maybe future features do help the dev with your money.

> 6. Try https://apkpure.com/noroot-data-firewall/com.jianjia.firewall and learn from it.

Link to the source code, so we all can learn from it?

> 1. "VPN DNS" is defauled to "8.8.8.8". I don't trust Google and due to its
hostile nature,

Setting up a VPN without a DNS will default it to 8.8.8.8, blame it on your Android/OEM, do build your own Android ROM to removes that _feature_.

> 2. You are forcing people to use/access netguard.me server. Related Bugs#2.

No, if you don't press download it won't contact the server, if you block NetGuard in NetGuard it can't connect to the server.
No, just delete that string or put https://github.com/Free-Software-for-Android/AdAway/blob/master/hosts/hosts.txt or whatever you want instead.
Yes, #195 would be nice.

> 3. Same thing goes to "[X] Check Update github" option. I use Fdroid to do that,

Yes, pretty clear that you did not read [FAQ#15](https://github.com/M66B/NetGuard/blob/master/FAQ.md#FAQ15)

> 3. If you're making true open source & free (not paid) app, try to remove "billing service"
> Why do you require them for "Firewall" app!?

Those to don't exclude each other, again app is feature complete without those.
You did not read anything at all, right? https://github.com/M66B/NetGuard#permissions

> I expected NetGuard as a pure firwall.

It is.

>  NetGuard connect to the Internet, especially netguard.me BY DEFAULT without user consent(on by default).

Block NetGuard in NetGuard, it won't connect if you disable version check and if you DO NOT PRESS THE DOWNLOAD HOSTS, if it does so do provide a logcat/PCAP or point in the source coe where it does all that by IT SELF.

> Fiwall should allow only selected apps; deny everything else.

Just toggle those in settings, not sure what you mean, it has this feature already.

> https://gitlab.com/fdroid/fdroiddata/issues/436
> This app trackes user by adding UniqueID when connecting to netguard.me.

PCAP with this, how did you find this? Proof?

> This app support NSA and Google by forcing people to use 8.8.8.8 Google DNS.

See above, don't use Android or build your own ROM.
BTW, when redirecting to your DNS of choice via port forwaring IT WILL SHOW 8.8.8.8 or any other VPN DNS as the destination, but IT WILL redirect traffic to YOUR DNS. Had to say that to avoid another useless issue creation.

Also, FFS, just inspect the code and build it yourself if you don't trust @M66B, or better yet compile yourself any other open-source no-root firewall, well if you have one, you do have another one, right?

**Comment by M66B** [comment]
I will comment on the F-Droid removal request only:

```
This app trackes user by adding UniqueID when connecting to netguard.me.
```
This is not true, check the source code.

```
This app support NSA and Google by forcing people to use 8.8.8.8 Google DNS.
```
This is not true, NetGuard defaults to the device DNS and you can set any DNS server you like.
