### ISSUE TITLE
Limit App Data Usage per Month

### ISSUE THREAD

**Issue by CrtcxnXt** [M66B/NetGuard#434]
Hi,

I'd like to suggest a feature to limit data usage per app per month. For example, occasionally, I accidentally turn off wifi but video chat on the data network via hangouts. While I would like to allow hangouts to use mobile data at all times to receive messages, I definitely do not want it to be used for video chats. If I can limit it to 100MB/month or whatever, this would prevent it from (or at least stop it) from going through my data limit if I accidentally video chat on the mobile network instead of wifi.

Thanks.

**Comment by quasarj** [comment]
What about also adding the ability to limit the current maximum speed of an individual app? To say 10kbps, for example. Or is this already possible?

**Comment by M66B** [comment]
Please create s new issue for this, but note this will not be a high priority features request, since it is, like this issue, far from the core function of NetGuard.

**Comment by M66B** [comment]
@CrtcxnXt you can also solve this by using the condition 'when screen on', so application can only use data while you are around. Another option is to use the widget (with a time set in the settings to turn NetGuard automatically on again after some time).

In general I see no point in limiting data usage per application, since (mobile) data limits are per subscription, not per application (although there are some exceptions to this, like unlimited Facebook access, but this can be done by just allowing the application).
