### ISSUE TITLE
Limit/block data connection on battery condition

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#455]
This can be achieved w/o root for Wi-Fi only on Android >= 5, IIRC.

Is a `block Wi-Fi and/or data connections if battery <??%` within NetGuard scope?

Case in point, Samsung ROMs don't have such a feature while vanilla and many OEMs have such a function in their battery settings.

**Comment by M66B** [comment]
Android sends an event to applications when power saving is enabled due to little battery remaining. It is up to the applications to implement this. NetGuard implements this by shutting down the network speed graph (this works only in the GitHub version). This is an example where an application can implement something better than just shutting off internet.

I am also sure this will result in additional support questions, which there are already enough.

Summarized, I am not willing to implement this.

**Comment by licaon-kter** [comment]
Ok, fair enough.
