### ISSUE TITLE
maps.me app can't download map

### ISSUE THREAD

**Issue by denicgrab2** [M66B/NetGuard#460]
Hi there and thanx for great guard!
I was found some sad mistake - maps.me application  (http://maps.me/ru/home) 
can't download map while netguard is active.
Any comments?

**Comment by M66B** [comment]
This is likely caused by blocking something, which could be a system component as well.
I don't think this is caused by a bug in NetGuard.
To check this, clear NetGuard data using the Android settings.

BTW, this kind of things are better discussed on XDA:
http://forum.xda-developers.com/android/apps-games/app-netguard-root-firewall-t3233012
