### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by marcelloh** [M66B/NetGuard#475]
VPN start failed

(run latest netguard on bluestack)

It won't start  up automatically.
Is there an option not to do that, so I can see if it starts by hand?

**Comment by M66B** [comment]
Some Android versions have a bug, which is the underlying cause of this message. IMHO it is better to notify that  autostarting  failed then to silently not start.

In most cases you can start manually later on. If you can't, then try to revoke VPN permission from NetGuard using the Android VPN settings.

**Comment by marcelloh** [comment]
I'm sorry, but a program should never throw an exception and show it to the end user. So in my book (I'm a programmer too), this is not a closed issue.

And I did ask a second question, since the program won't autostart: is there a way not to let it autostart? So by not answering that part if the issue, it's not closed either.

**Comment by M66B** [comment]
The exception is only shown to users when NetGuard was not installed from the Play store, because it is assumed people using the GitHub version are more expert users.

NetGuard will attempt to autostart when you shutdown your device with NetGuard enabled, so you can disable NetGuard and shutdown your device to prevent NetGuard from attempting to autostart.
