### ISSUE TITLE
IP filtering, ad blocking

### ISSUE THREAD

**Issue by licaon-kter** [M66B/NetGuard#79]
I wanted to postpone this until you got your ideas/workflow on paper/in code, so anyway...

1. How do you get the filtering done? Outside the VPN, on INPUT? Like a HOSTS file?

2. HOSTS file like means grabbing the DNS query and replying to it with 0.0.0.0?

3. By IPs sounds pretty straight forward, if you have IP already

4. Most of the lists need some sort of preprocess, if HOSTS like, to let only the hosts and clean the 127.0.0.1 or 0.0.0.0 redirecting.

5. Most of the ads/malware/tracking lists have domain names, you could preemptivly/schedule (or say on user toggle, only on Wi-Fi and so on) resolve their IPs and keep it sorted/uniqued/cached locally. It takes a while, bandwidth, CPU power, but you do it once in a while, not often.

6. IP lists are kinda worse then, you will have servers hosting multiple sites, blocking the legit one with the bad one.

7. Whitelist, you'll get the ocassional site that brakes, you need to add exceptions, globally first.

8. For whitelist and not only, you need find the domain/IP thats wrongfully blocked so you intercept/log per app calls, you make a per app connection list ( IP and address ). So you end up with: per app custom IPs/address, per app lists, per app whitelist.

9. Once you find the domain/IP that is blocked maybe it is useful to point out from what list it came, maybe so one can whitelist/report it upstream if blocked wrongfully or if site cleaned up in the mean time.

10. Default lists, I find [uBlock origin](https://github.com/gorhill/uBlock/tree/master/assets/thirdparties) / [uMatrix](https://github.com/gorhill/uMatrix/tree/master/assets) ones pretty ok, listed below for convenience. One needs permission to include them? To pull them from the app by the user? Needs investigating maybe.

HOSTS format:
* [Dan Pollock’s hosts file‎](http://someonewhocares.org/) -> [raw list](http://someonewhocares.org/hosts/hosts) 
* [hpHosts’s Ad and tracking servers‎](http://hosts-file.net/) -> [raw list](hosts-file.net/ad-servers.txt) 
* [Malware Domain List‎](http://www.malwaredomainlist.com/) -> [raw list](www.malwaredomainlist.com/hostslist/hosts.txt) 
* [MVPS HOSTS‎](http://winhelp2002.mvps.org/) -> [raw list](http://winhelp2002.mvps.org/hosts.txt) 

Just domains format
* [Long-lived malware domains](http://malwaredomains.lehigh.edu/) -> [raw list](http://mirror1.malwaredomains.com/files/immortal_domains.txt) 
* [Malware domains‎](http://malwaredomains.lehigh.edu/) -> [raw list](mirror1.malwaredomains.com/files/justdomains) 

Can be customized
* [Peter Lowe’s Ad server list‎](http://pgl.yoyo.org/ads) -> [raw list](http://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml&showintro=0&startdate%5Bday%5D=&startdate%5Bmonth%5D=&startdate%5Byear%5D=)

That's what I have in mind for the moment. :)

**Comment by M66B** [comment]
The main problem is that filtering needs to be done based on IP addresses, assuming no root. So, domain names need to be translated into IP addresses, which is problematic, because a domain name doesn't need to have a fixed set of addresses (for example when the popular service [CloudFare](https://www.cloudflare.com/) is being used).

The other, maybe obvious, disadvantages are:

* Higher battery use, due to CPU load
* Bandwidth reduction, due to CPU limits
* Internet permission required, to tunnel allowed traffic to the internet

A less obvious problem is determining the original application of a packet. I have figured out how to do this (the implementation is in the Packet class and this may very well even be the first open sourced code for that), but Google can block this in future Android releases with new SELinux policies, stopping it from working.

Actually this project started as an IP filtering VPN experiment (source code partly available on GitHub in the Packet class and some debug code in the Sinkhole service). This will answer your first question, provided we want to stick to no root. Altering the hosts file requires root.

So, the options with no root are limited and there are quite some disadvantages and that is why I didn't base an application on it. In the process of experimenting I got the idea for the current implementation, not having all the disadvantages, but also not the features.

**Comment by licaon-kter** [comment]
I know about hosts and root, I meant a hosts-like idea, given [the way it works now](https://github.com/M66B/NetGuard/commit/f9b1f1f3092e7de4db092c5a5602eadc0b9fd163#commitcomment-14248160), if you do it the _other_ way, tunnel allowed stuff into the VPN, disallow blocked apps, once in the tunnel don't you have full control of the packets?

**Comment by M66B** [comment]
In the tunnel there is full control of packets, but the tricky thing is to determine the sending application.

**Comment by licaon-kter** [comment]
For starters, no per app filtering, everything ( allowed that is ) goes in to the tunnel and gets filtered.

**Comment by M66B** [comment]
Per application filtering is needed, else the firewall settings cannot be applied per application.

**Comment by licaon-kter** [comment]
You can't apply them for **all** the VPN tunnelled traffic?

**Comment by M66B** [comment]
Let me explain in more details: for IP-filtering *all* traffic needs to be routed into the VPN tunnel and allowed traffic needs to be forwarded (hence the *internet* permission requirement). Allowed traffic means not blocked with a firewall rule per application *and* not blocked globally (ad block, etc).

**Comment by LifeIsStrange** [comment]
I don't know if this can help you but the efficient and powerfull content blocker uBlock Origin use this method https://github.com/gorhill/publicsuffixlist.js

**Comment by licaon-kter** [comment]
So this should be closed for the moment?

**Comment by M66B** [comment]
No, because it is still a feature request, one which will be requested again when closed.

**Comment by M66B** [comment]
I am closing this issue, because I think new SELinux policies will make it impossible to determine which application was sending an IP packet in the near future. Most of the existing no-root firewall solutions will stop working if this happens and I don't want this to happen to NetGuard.

**Comment by licaon-kter** [comment]
Do reopen this...



Anyway, testing: filtering now works as in *it blocks all traffic*, not sure if that was intended though. 
Yes the log shows the app an the little blue icon, but it can't access the internet.

**Comment by M66B** [comment]
For me it works, so make your you have built with the latest commits. Else I need a logcat and a pcap.

**Comment by M66B** [comment]
I have fixed on issue in TCP ACK handling this morning, which might explain the problem you had.

**Comment by licaon-kter** [comment]
What's the hosts file format?

**Comment by M66B** [comment]
Standard hosts file format, as Linux and Windows are using.
See the release announcement on XDA for a link to examples.

**Comment by licaon-kter** [comment]
I looked around but did not see it so bare with me, do you respect the IP for the redirection?

**Comment by M66B** [comment]
Domain blocking is done on domain names.

**Comment by licaon-kter** [comment]
So unlike classic hosts file, no redirection, you ignore the IP and extract just the domain to block, right?

**Comment by M66B** [comment]
Yes, the requested domain name is compared with the domain names in the hosts file.
The IP address in the hosts file is ignored.

**Comment by licaon-kter** [comment]
What's the difference between `filter traffic` and `filter traffic + block domain names` ?

**Comment by licaon-kter** [comment]
Also, testing this list https://github.com/StevenBlack/hosts having both filter and block domain, I seem to be able to load an address listed there, tested with `gsmtop dot net`.

**Comment by M66B** [comment]
Filter traffic: the traffic is routed through the VPN and later you can add rules to allow/deny IP addresses globally and per application.

Block domain names requires IP filtering, since the traffic needs to go through the VPN for this option. Currently domain names (not IP addresses) can be blocked globally based on a imported hosts file. Later  you will be able to allow/deny per application.

Regarding the host file, please create an issue to directly import from a provided URL.
In this issue you can propose URLs like the one in your comment.

**Comment by licaon-kter** [comment]
That issue is here, and different: https://github.com/M66B/NetGuard/issues/249

Ok I got the difference, I knew that already, although at this moment I'm not sure why `filter` all by itself exist, if you are not blocking what's the advantage or what else can be done by using the VPN? Battery usage aside.

**Comment by M66B** [comment]
As explained above, all traffic is flowing through the VPN in filter mode, which allows for a range of new features, like IP blocking. It will also fix the block all problem of some devices and will allow lowering the required Android version to ICS.

Example use: inspect http requests for privacy sensitive data.

**Comment by licaon-kter** [comment]
So this is a future options enabler.

**Comment by M66B** [comment]
Yes, except for two things:

* Domain blocking depends on it
* It will fix the all traffic blocked for some devices

I have released it to get the code tested, since I want to have a stable, proven core before going into the UI.
